### PR TITLE
Added unit tests for pdf, csv, txt, md, url loaders

### PR DESCRIPTION
**Pull request by TekuriSaiAkhil**
1. Created a test folder in features/dynamoExtendedFileSupport
2. Added unit tests to test pdf, csv, txt, md, URL, pptx, docx, xls, xlsx, xml loaders in [test_loaders.py](https://github.com/AaronSosaRamos/kai-ai-backend/pull/1/files#diff-ca949781649b2936b60474da8b8ef5e6bd44063f5c1b9172a250e27865d9b2d5)
3. Made small changes in [tools.py](https://github.com/AaronSosaRamos/kai-ai-backend/pull/1/files#diff-74e8e998c892da775245f0434a593773f26b57d4fcec57fbcad39e2d0cf577e2) to return the pages instead of print. This helps to validate loader outputs in unit tests

### CODE REVIEW

**Comment by AaronSosaRamos** [comment]
Good job @TekuriSaiAkhil. Can you please do `git pull` and test your imp. again? Because I've implemented new security management for our document loaders.

**Comment by TekuriSaiAkhil** [comment]
> Good job @TekuriSaiAkhil. Can you please do `git pull` and test your imp. again? Because I've implemented new security management for our document loaders.

Included the latest changes and added unit tests for pptx, docx, xls, xlsx, xml loaders as well. @AaronSosaRamos please take a look

**Comment by AaronSosaRamos** [comment]
I've see this error when I run the unit tests: 
image
I think that this happens due to some dependency errors which happened due to the use of uvicorn as it somestimes doesn't consider all the imports. 
But it doesn't only happen in your file, it also happens in the existent tests from Quizzify:
image
Do `git pull` again as I'll try to run the unit tests again in the Docker container.

**Comment by TekuriSaiAkhil** [comment]
> I've see this error when I run the unit tests: image I think that this happens due to some dependency errors which happened due to the use of uvicorn as it somestimes doesn't consider all the imports. But it doesn't only happen in your file, it also happens in the existent tests from Quizzify: image Do `git pull` again as I'll try to run the unit tests again in the Docker container.

add `export PYTHONPATH=$PYTHONPATH:/Users/tekurisaiakhil/Desktop/kai-ai-backend` replace path with your project directory if you want to test it ourside docker

**Comment by TekuriSaiAkhil** [comment]
Before running tests, please do `pip install -r requirements.txt` in your virtual env

**Comment by AaronSosaRamos** [comment]
Thank you @TekuriSaiAkhil. I'll test it. Now, I've done another updates for improving the experience of using Google Drive files. Do `git pull` again and try to do the Unit Tests for the new Google Drive document loaders.

**Comment by TekuriSaiAkhil** [comment]
> Thank you @TekuriSaiAkhil. I'll test it. Now, I've done another updates for improving the experience of using Google Drive files. Do `git pull` again and try to do the Unit Tests for the new Google Drive document loaders.

1. I have added Unit tests for new Google Drive document loaders.
2. I've added `def get_summary(full_content: str):
    chain = build_chain()
    return chain.invoke(full_content)` in tools in order to remove code repetition in tools.py
3. Made `file_loader(file_url, verbose)` return `full_content` and called `get_summary(full_content)` to get the summary

@AaronSosaRamos 
I found this is more optimized In terms of code duplication and testing. Also I suggest to get these unit tests merged before further development in main

**Comment by AaronSosaRamos** [comment]
Good job @TekuriSaiAkhil! I've checked your code and it helps us to reduce code redundancy. What is lastly required is to do a last `git pull` and solve the conflitcs with these files: core.py and tools.py. With that, I think that we accomplished Task 4!

**Comment by AaronSosaRamos** [comment]
LGTM. Well done! @TekuriSaiAkhil

**Pull request merged**
