### PR TITLE
Task 5

### PR DESCRIPTION
**Pull request by TekuriSaiAkhil**
Only to be merged after this PR https://github.com/AaronSosaRamos/kai-ai-backend/pull/1 

1. Added flask card generation feature
2. Re-organised the code between core.py and tools.py to reflect the format of "dynamo.core" and "dynamo.tools"

### CODE REVIEW

**Comment by AaronSosaRamos** [comment]
Hi @TekuriSaiAkhil. Here are some indications:
1. Add a mechanism for managing edge cases when there are no available key concepts. Just return an empty list. 
image

**Comment by AaronSosaRamos** [comment]
2. Refactor the "prompt/summarize-xlsx-csv-prompt.txt" so that we can gather key concepts from the tables' attributes (CSV/XLS/XLSX/Sheet) and its posible relations. Be careful of these types of responses:
image

**Comment by AaronSosaRamos** [comment]
3. Be careful with the fourth app type as I retrieve an error from `generate_concepts_from_img `method: 
image

**Comment by TekuriSaiAkhil** [comment]
@AaronSosaRamos, Resolved these issues

In case of no available key concepts, Returned the empty list and logged the error:
> Hi @TekuriSaiAkhil. Here are some indications:
> 
> 1. Add a mechanism for managing edge cases when there are no available key concepts. Just return an empty list.
>    image

**Comment by TekuriSaiAkhil** [comment]
Updated the "summarize-xlsx-csv-prompt.txt". I can see better output responses for CSV, xlsx files
Sample respinse for "https://filesamples.com/samples/document/csv/sample1.csv" as input:
Screenshot 2024-06-27 at 3 23 29 PM

> 2. Refactor the "prompt/summarize-xlsx-csv-prompt.txt" so that we can gather key concepts from the tables' attributes (CSV/XLS/XLSX/Sheet) and its posible relations. Be careful of these types of responses:
>    image

**Comment by TekuriSaiAkhil** [comment]
Fixed issue with generate_concepts_from_img. Incase the JSON is not valid return the empty list

> 3. Be careful with the fourth app type as I retrieve an error from `generate_concepts_from_img `method:
>    image

**Comment by AaronSosaRamos** [comment]
LGTM. I will refactor the csv/xlsx/xls/sheet prompt in base of your support @TekuriSaiAkhil.

**Pull request merged**
