### PR TITLE
add multi-lang support & fixed Chroma multiple creation issue

### PR DESCRIPTION
**Pull request by Tptrix29**
I fixed the issue that vector database is created repeatedly and add multi-language support for worksheet generation.
Sample JSON Request:
```json
{
    "user": {
        "id": "string",
        "fullName": "string",
        "email": "string"
    },
    "type": "chat",
    "tool_data": {
        "tool_id": 2,
        "inputs": [
            {
                "name": "grade_level",
                "value": "College"
            },
            {
                "name": "topic",
                "value": "Painting"
            },
            {
                "name": "worksheet_list",
                "value": [
                    {
                        "question_type": "fill_in_the_blank",
                        "number": 1
                    },
                    {
                        "question_type": "relate_concepts",
                        "number": 1
                    },
                    {
                        "question_type": "open_ended",
                        "number": 2
                    }
                ]
            },
            {
                "name": "file_url",
                "value": "https://www.yorku.ca/yamlau/readings/greenberg_modernistPainting.pdf"
            },
            {
                "name": "file_type",
                "value": "pdf"
            },
            {
                "name": "lang", 
                "value": "zh"
            }
        ]
    }
}
```

### CODE REVIEW

**Comment by AaronSosaRamos** [comment]
This is a great approach @Tptrix29, good job! I think that you can also add a way about handling errors in the question generation because I tested your PR with different langs and it worked in almost 98% of the cases. But there was a case where I received a JSONOutputError, which is really undeterministic but I think that we can handle it with a similar approach than what was done on `quizzify/tools.py`. 
image

**Comment by AaronSosaRamos** [comment]
Also, don't forget to solve the conflicts from your branch please.
image

**Comment by Tptrix29** [comment]
I have fixed issues related to JSON output errors and removed the API key while solving the conflicts

**Comment by AaronSosaRamos** [comment]
LGTM.

**Pull request merged**
